### ISSUE TITLE
gitpoller: exceptions must be classes or instances deriving from BaseException, not type 

### ISSUE THREAD

**Issue by aliceinwire** [GKernelCI/GBuildbot#133]
```
buildbot_1               | 2021-02-13 09:28:45+0000 [-] trying to poll branch refs/heads/4.1 of https://github.com/GKernelCI/linux-patches.git
buildbot_1               |      Traceback (most recent call last):
buildbot_1               |        File "/usr/lib/python3.8/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
buildbot_1               |          current.result = callback(current.result, *args, **kw)
buildbot_1               |        File "/usr/lib/python3.8/site-packages/twisted/internet/defer.py", line 1475, in gotResult
buildbot_1               |          _inlineCallbacks(r, g, status)
buildbot_1               |        File "/usr/lib/python3.8/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
buildbot_1               |          result = result.throwExceptionIntoGenerator(g)
buildbot_1               |        File "/usr/lib/python3.8/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
buildbot_1               |          return g.throw(self.type, self.value, self.tb)
buildbot_1               |      --- <exception caught here> ---
buildbot_1               |        File "/usr/lib/python3.8/site-packages/buildbot/changes/gitpoller.py", line 220, in poll
buildbot_1               |          yield self._process_changes(revs[branch], branch)
buildbot_1               |        File "/usr/lib/python3.8/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
buildbot_1               |          result = result.throwExceptionIntoGenerator(g)
buildbot_1               |        File "/usr/lib/python3.8/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
buildbot_1               |          return g.throw(self.type, self.value, self.tb)
buildbot_1               |        File "/usr/lib/python3.8/site-packages/buildbot/changes/gitpoller.py", line 311, in _process_changes
buildbot_1               |          results = yield self._dovccmd('log', revListArgs, path=self.workdir)
buildbot_1               |        File "/usr/lib/python3.8/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
buildbot_1               |          result = result.throwExceptionIntoGenerator(g)
buildbot_1               |        File "/usr/lib/python3.8/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
buildbot_1               |          return g.throw(self.type, self.value, self.tb)
buildbot_1               |        File "/usr/lib/python3.8/site-packages/buildbot/changes/gitpoller.py", line 405, in _dovccmd
buildbot_1               |          stdout = yield self._dovccmdImpl(command, args, path, None)
buildbot_1               |        File "/usr/lib/python3.8/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
buildbot_1               |          result = result.throwExceptionIntoGenerator(g)
buildbot_1               |        File "/usr/lib/python3.8/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
buildbot_1               |          return g.throw(self.type, self.value, self.tb)
buildbot_1               |      builtins.TypeError: exceptions must be classes or instances deriving from BaseException, not type
```

**Comment by aliceinwire** [comment]
opened issue to buildbot https://github.com/buildbot/buildbot/issues/5794
